### ISSUE TITLE
CSP3: 'no-console-log' directive being considered

### ISSUE THREAD

**Issue by april** [whatwg/console#110]
As suggested by @annevk, I'm opening up an issue to make folks aware that I have proposed a `no-console-log` directive as part of CSP3. This is intended as a way for sites to reduce the amount of CSP error logging that can happen when a significant number of resources are blocked:

https://github.com/w3c/webappsec-csp/issues/217

**Comment by domfarolino** [comment]
Thank @april for filing the issue. Given the included thread, I'm going to close this as it seems there's not much on our side to do for this, and the requested filtering is outside the scope of CSP and could better appear as some sort of filter in the Developer Tools for a browser.
