### ISSUE TITLE
Update format specifier table's %s entry

### ISSUE THREAD

**Issue by domfarolino** [whatwg/console#136]
A while back, https://github.com/whatwg/console/pull/123 specifically, we opted to use the built-in String constructor for `%s` format specifier conversions. This ensures that when the `%s` specifier was applied to a `Symbol`, the console method performing this action wouldn't throw an error. Previously in the spec we used [ToString](https://tc39.github.io/ecma262/#sec-tostring) which _would_ throw errors. The [format specifiers](https://console.spec.whatwg.org/#formatting-specifiers) table in this spec still has a leftover [ToString](https://tc39.github.io/ecma262/#sec-tostring) reference that needs to be changed to reference the built-in String constructor.

**Comment by terinjokes** [comment]
:+1:
