### ISSUE TITLE
Should console.profile[End] be specced?

### ISSUE THREAD

**Issue by saschanaz** [whatwg/console#144]
Those two methods are not mentioned in #27 but it seems both are available on Chrome, Firefox and Edge.

**Comment by saschanaz** [comment]
It seems they are already emitting deprecation notice or just non-functional.

**Comment by julienw** [comment]
They work in Firefox without emitting deprecation notice with the  current performance panel-- but we're considering deprecating them by not implementing them in the new performance panel in https://bugzilla.mozilla.org/show_bug.cgi?id=1499694.

In Chrome they don't work properly but don't emit any deprecation notice either.
