### ISSUE TITLE
Allow libraries opt-in to analytics/stats gathering with reportLibrary()

### ISSUE THREAD

**Issue by justinfagnani** [whatwg/console#149]
Projects like https://github.com/johnmichel/Library-Detector-for-Chrome try to detect library usage on a page for analytics. As modules, WeakMap and eventually private stage become more popular, many libraries won't leave any signatures that can be detected on a page.

If they want to be countable, they'd have to explicitly leave a fingerprint, like say `window.usesLodash = true`. At that point, it might make sense to offer an explicit API for this.

`console` could provide a simple API, like `reportLibrary(name, version)` that can be queried by other tools or sent to ReportingObservers. This call would be unambiguous and survive bundling, minification, etc.

**Comment by domfarolino** [comment]
Hmm, while interesting, I think it may fall a little out of the Console API's scope to be responsible for reporting something so specific, and might be better left to another library or something of that vein to provide this. This is my initial take, but I'd be interested to hear @domenic's.

**Comment by domfarolino** [comment]
After speaking a bit on IRC with Domenic, I think this falls out of Console's scope, and would best be for some other library or perhaps a Reporting API. Thanks for filing.

**Comment by JoelEinbinder** [comment]
Chrome DevTools is interested in this. Libraries are already using the console for this purpose, but having a standard we can parse would open a lot of new features. For example, recommended extensions for those libraries.

Another option would be to hijack `console.info` with some special parameters as a signal that this a library name. `console.info('using-product', { product: 'lit-html', version: '300234' });`. But that feels hacky.

**Comment by nchevobbe** [comment]
I like the idea of being able to query a content page in order to know what libraries are used on it, so we can provide extension recommendation. What I don't know is where this fits.
I feel like the console API is pretty well constrained and is for user's consumption, not tools/browser's.

A different API might be the solution, or some new attributes in `<meta>` that those libraries could append in the document (drawback being it wouldn't be usable in Node)

**Comment by JoelEinbinder** [comment]
> I feel like the console API is pretty well constrained and is for user's consumption, not tools/browser's.

That's fair. But what about `console.dir` and `console.dirxml`? What are they for, if not as a hint to tools on how to present the information?

> A different API might be the solution, or some new attributes in `<meta>` that those libraries could append in the document (drawback being it wouldn't be usable in Node)

This wouldn't be usable in workers, or multi-document applications. I'm also worried it would unintentionally encourage libraries to sniff eachother's meta tags.

**Comment by domfarolino** [comment]
> What are they for, if not as a hint to tools on how to present the information?

I think the tools they are informing are mostly native developer tools right? I don't believe that they provide hooks for application code to be pulled in/notified on certain things.

I don't think there is any precedent for application code being able to consume console output. In some cases, there are good [security reasons for this](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/loader/subresource_integrity.cc?q=subresource_integrity.cc&sq=package:chromium&g=0&l=152). Of course it seems like `reportLibrary` wouldn't have any UA-generated info to leak, but I am not really convinced that `reportLibrary` is in-scope for the Console standard. I think it'd best belong elsewhere.

**Comment by JoelEinbinder** [comment]
> > What are they for, if not as a hint to tools on how to present the information?
> 
> I think the tools they are informing are mostly native developer tools right? I don't believe that they provide hooks for application code to be pulled in/notified on certain things.
> 
> I don't think there is any precedent for application code being able to consume console output. In some cases, there are good [security reasons for this](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/loader/subresource_integrity.cc?q=subresource_integrity.cc&sq=package:chromium&g=0&l=152). Of course it seems like `reportLibrary` wouldn't have any UA-generated info to leak, but I am not really convinced that `reportLibrary` is in-scope for the Console standard. I think it'd best belong elsewhere.

Ah, I misunderstood `reportLibrary`. I agree! I'll file my own issue.
