### ISSUE TITLE
Address security warning on the reference implementation

### ISSUE THREAD

**Issue by annevk** [whatwg/console#152]
lodash needs to be at least 4.17.5 per GitHub alerts.

**Comment by domfarolino** [comment]
Ok I'll look into this. There was talk of ripping out the reference implementation I think, so I'll confirm that before taking action.

**Comment by annevk** [comment]
Any update here?

**Comment by domfarolino** [comment]
I feel like their was more discussion on ripping out the reference implementation for this spec, but I could only find https://github.com/whatwg/console/issues/141#issuecomment-392399825 which was me alluding to this "more discussion". Anyways, I've posted https://github.com/whatwg/console/pull/180 remove the reference implementation, which I think is mostly unused these days.

**Comment by annevk** [comment]
It seems that didn't fix this though, as this is a dependency in the tests.

**Comment by domfarolino** [comment]
Oh I see. Apologies, thank you.
