### ISSUE TITLE
add Abbreviation log for console.log such as dir for console.dir

### ISSUE THREAD

**Issue by zhangenming** [whatwg/console#166]
we frequent use console.log
if we have this abbr. very convenient

**Comment by domfarolino** [comment]
I don't follow. Could you explain?

**Comment by zhangenming** [comment]
sorry i mean 
when i want log a value  i must `console.log(value)`
if we have the Abbreviation  log for console.log we can `log(value)`

**Comment by domfarolino** [comment]
Thanks for filing the issue, but I think this is sort of out-of-scope for the spec to define. You should be able to get what you want by setting `log = console.log` in your script, if you want to use the `log` abbreviation. Let me know if I can clarify anything.
