### ISSUE TITLE
Pushing on a group stack not defined

### ISSUE THREAD

**Issue by annevk** [whatwg/console#188]
The document is/was using `<a>Push</a>`, but that didn't reference a meaningful algorithm for what it was trying to do.

I'm removing the wrapper link in https://github.com/whatwg/console/pull/187 to fix the build.

**Comment by domenic** [comment]
The intent was to use https://infra.spec.whatwg.org/#stack-push

**Comment by annevk** [comment]
Alright, updated the PR to use that. I guess that's fine then.
