### ISSUE TITLE
feature request: add `console.color`

### ISSUE THREAD

**Issue by idanran** [whatwg/console#217]
```ts
interface color {
level: 0 | 1 | 2 | 3
noColor: boolean
bit4: boolean
bit8: boolean
bit16: boolean
}
```

**Comment by terinjokes** [comment]
I'm not sure this is something that makes sense for this specification. How logged messages are displayed to the user is up to the user agent, and the user agent may be displaying, storing, or transmitting messages to multiple sinks at the same time.

**Comment by domfarolino** [comment]
I'm in agreement. This, along with the already-available `%c` format specifier to provide CSS for console output makes me think there would be little vendor appetite for this, and that this probably best belongs not in this spec.
