### ISSUE TITLE
Needs a Twitter account that tweets commits

### ISSUE THREAD

**Issue by domenic** [whatwg/console#22]
I guess I can do this since I think only admins have permission to change webhooks.

**Comment by robertkowalski** [comment]
yes, i can confirm I can't edit anything for the repo.

**Comment by domenic** [comment]
Did someone just register https://twitter.com/consolestandard ? I swear it was a 404 a minute ago.

**Comment by robertkowalski** [comment]
nope.

we should contact twitter support if it was squatted.

i think the twitter api tells when a user registered their account and twitter should know anyway.

**Comment by robertkowalski** [comment]
@domenic should we setup another account?

**Comment by domenic** [comment]
Yeah we should, I can work on it. I am afraid to put ideas in this thread because they might get taken like that one did :(

**Comment by robertkowalski** [comment]
i am sure you will come up with a good one, but you can also ping me on irc :)

**Comment by frewsxcv** [comment]
just preemptively registered twitter.com/consolespec 

if you want the credentials, shoot me an email or pm me on irc

**Comment by robertkowalski** [comment]
cool! glad that it seems to work out!

**Comment by domenic** [comment]
Thanks @frewsxcv for the offer! @terinjokes was able to get the [@consolelog](https://twitter.com/consolelog) Twitter account, which is a pretty great name (it's a commit _log_ ... for a spec about console.log... so good!).

I set up the account with the usual stuff and also used my admin powers to set up the web hook, so any future commits should be tweeted. Still TODO, but not by me:

- Tweet a nice first "hello world" tweet maybe, instead of just starting with commit messages. Up to you. Maybe `console.log("Hello world! It's time to finally spec me!") https://console.spec.whatwg.org/`.
- Add the Twitter account to the header of the spec. See streams or URL for an example.
- Maybe @terinjokes could add a line to the acknowledgments about the nice person who gave us the Twitter account.

**Comment by terinjokes** [comment]
I think we should use some of those format specifiers :grinning: 

```
console.log("Hello %s! I'm finally getting a standard! %s", userName, "https://console.spec.whatwg.org/")
```

I can make both edits once we get the first tweet out.

**Comment by annevk** [comment]
WHATWG is following. Hopes to retweet soon.

**Comment by terinjokes** [comment]
Tweeted: https://twitter.com/consolelog/status/689594121523109888
