### ISSUE TITLE
add `console.log` function to window, so we can use `log` direct!

### ISSUE THREAD

**Issue by zhangenming** [whatwg/console#221]
now, we have window.dir,
So why can't we have it.
thanks

**Comment by domfarolino** [comment]
Interesting, do you know where `dir()` is defined in the spec? It seems like a non-standard API that is not available to Safari or Firefox.

**Comment by zhangenming** [comment]
https://developer.chrome.com/docs/devtools/console/utilities/#dir-function

**Comment by terinjokes** [comment]
That's not a property on window, but a custom shortcut implemented inside of Chrome's Developer Tools.

**Comment by zhangenming** [comment]
Yes, this variable only exists when Chrome's Developer Tools is open.
but `console.log` is such a common method, may you can provide a simpler one with fewer keystrokes for easy input?like `log`.
tks

**Comment by domfarolino** [comment]
I feel pretty certain that this could be solved by some basic JS that aliases `log` to `console.log` etc. I don't think this really needs a lot of platform buy-in. I'm going to close this, but thanks for filing.
