### ISSUE TITLE
What should `console.assert(false, { a: 1 })` print?

### ISSUE THREAD

**Issue by jcbhmr** [whatwg/console#226]
gist of it: which one of these is the "right" way?
![image](https://github.com/whatwg/console/assets/61068799/91e8ea57-2595-457d-adcc-b1a5e0b40a8f)
![image](https://github.com/whatwg/console/assets/61068799/f231e997-b809-42af-a02c-d24406140420)

https://github.com/nodejs/node/issues/49680
https://github.com/mdn/content/issues/29172

it seems from the spec https://console.spec.whatwg.org/#assert that it all gets funneled to `Logger()` which unfurls all that `data` stuff the same way regardless of which `console.*` method was used but then again MDN says this:
![image](https://github.com/whatwg/console/assets/61068799/e5a01cca-6991-43f1-a0ce-ccffb93de3da)
as cited here https://github.com/nodejs/node/issues/49680?notification_referrer_id=NT_kwDOA6PV_7M3NzQ0NjE3OTU0OjYxMDY4Nzk5#issuecomment-1722528493
https://developer.mozilla.org/en-US/docs/Web/API/console/assert

...soooo yeah I opened this issue to hopefully get someone who knows how to read specs to clarify which way is the "spec way" or if I'm misunderstanding something 🤷‍♂️😵

**Comment by domfarolino** [comment]
Can you clarify your question? Which output is unexpected for you, and why?

**Comment by terinjokes** [comment]
I'd argue, as above, that both are correct. How any arguments, outside of specifiers, are printed is implementation defined, so `[object Object]` is equally correct as `{"hello": "world"}`. I don't think MDN's language is technically wrong (a string, of some sort, is printed), but it also implies behavior that isn't in the specification, and isn't found in their description of other logging method.

I would expect, in most environments, objects printed in `assert` in a similar fashion to how they're printed in the other logging method. However, as it's implementation defined, they may chose not to.

**Comment by jcbhmr** [comment]
I found an edge case that exemplifies Node.js' implementation as being buggy:
```js
console.assert(false, Symbol())
// THROWS! becase `Assertion failed: ${Symbol()}` will fail
```

and I've also changed my MDN issue to focus on improving the wording on a bunch of the console methods. https://github.com/mdn/content/issues/29172

**Comment by jcbhmr** [comment]
@terinjokes Yep! You answered my question! ❤️ Thanks for clarifying the implementation-defined nature of the printing and explaining the spec logic for me. 👍

**Comment by terinjokes** [comment]
The fact that Node.js prints `[object Object]` only for the first object is curious. Without reviewing the code it suggests to me that it's converting the second parameter to a string either to concatenate with the "Assertion failed" message, or to check for specifiers (or both), neither of which would be following this standard.

**Comment by jcbhmr** [comment]
Yep! Here's the relevant bit:
```js
  assert(expression, ...args) {
    if (!expression) {
      args[0] = `Assertion failed${args.length === 0 ? '' : `: ${args[0]}`}`;
      // The arguments will be formatted in warn() again
      ReflectApply(this.warn, this, args);
    }
  },
```
https://github.com/nodejs/node/blob/cd97e28860d109e1576e05b4b79692aa013a4e6e/lib/internal/console/constructor.js#L435

Note that it **always** treats `args[0]` as a format string (coercing it) which is why `${Symbol()}` throws.

I've chosen to focus on that particular edge case to try and exemplify how the implementation isn't spec compliant in https://github.com/nodejs/node/issues/49680
