### ISSUE TITLE
Abstract operations are not getting linked correctly

### ISSUE THREAD

**Issue by domenic** [whatwg/console#24]
E.g. ToString should link to the ES spec, and Formatter() should link to the formatter AO.

This is probably a bug in emu-algify, so assigning to me.

**Comment by robertkowalski** [comment]
yes I also noticed that some time ago: https://github.com/domenic/emu-algify/issues/1

**Comment by domenic** [comment]
Wow, for some reason I was not watching my own repo :( Thanks for filing.
