### ISSUE TITLE
Clarify formatting specifiers a bit

### ISSUE THREAD

**Issue by domenic** [whatwg/console#25]
Right now the section https://console.spec.whatwg.org/#formatting-specifiers is kind of disconnected from the main text. https://console.spec.whatwg.org/#formatter handles some of them, but the ones that require complex UI are ignored by the rest of the spec's algorithms.

I am not sure how best to reconcile this. Maybe Formatter() should reference the tables in #formatting-specifiers, and remove the algorithm steps? Maybe Formatter() should get an additional line for each of %o, %O, or %c? But these don't act like type conversions, exactly...

In any case one goal should be to ensure there is only one normative source of truth---either the algorithm or the tables. If we decide on the algorithm being normative, then we can keep the tables, we just need to mark them non-normative.

**Comment by terinjokes** [comment]
My vote would be to have the algorithms as normative and have the tables as non-normative reference.

**Comment by robertkowalski** [comment]
i agree with terin, i would also prefer that and also mentioned it in https://github.com/whatwg/console/issues/6#issuecomment-170396383
