### ISSUE TITLE
Add a NOTE about "not async" behavior

### ISSUE THREAD

**Issue by domenic** [whatwg/console#39]
#38 and the related Firefox fix could maybe be called out more explicitly in the spec. I would suggest a non-normative NOTE something like this, after the Logger algorithm.

> It's important here that the printing occurs before returning from the algorithm. Many developer consoles print the result of the last operation entered into them. In such consoles, when a developer enters `console.log("hello!")`, this should first print `"hello!"`, _then_ the `undefined` return value from the `console.log` call.

You could even include an example screenshot showing this behavior.

**Comment by bgrins** [comment]
@domenic I can help with this.  If I take a screenshot then in what folder should that be added?

**Comment by bgrins** [comment]
Also, I think #37 is the relevant issue

**Comment by bgrins** [comment]
Went ahead and added an images/ directory and put a rule for it in the Makefile
