### ISSUE TITLE
Bikeshed killed the spec; also, we shouldn't let this happen again

### ISSUE THREAD

**Issue by domenic** [whatwg/console#43]
If the build fails, we shouldn't deploy. Oops.

https://console.spec.whatwg.org/

**Comment by domenic** [comment]
OK, fixed the spec.

To get curl to fail on a Bikeshed error, you pass -f to curl. But, my Unix-foo isn't strong enough for the next step: when we pipe the failure to emu-algify, it just sees an empty document. How do we tell a Unix pipe chain that if the first command exits nonzero, it should bail, instead of continuing?

**Comment by terinjokes** [comment]
@domenic this StackOverflow gives a couple suggestions: http://stackoverflow.com/questions/25306774/best-way-to-handle-pipes-and-their-exit-status-in-a-makefile

**Comment by domenic** [comment]
Thanks for digging that up; works great.

**Comment by robertkowalski** [comment]
ouch, thanks for fixing!
