### ISSUE TITLE
Add a console.* API that invokes the HTML "report the error" algorithm (which calls window.onerror)

### ISSUE THREAD

**Issue by annevk** [whatwg/console#50]
See https://lists.w3.org/Archives/Public/public-web-perf/2014Jun/0036.html and https://esdiscuss.org/topic/a-way-of-explicitly-reporting-exceptions for interest.

See https://www.w3.org/Bugs/Public/show_bug.cgi?id=26182 for the previous issue on this (merged into this new one since the idea seems to be to have it on console).

**Comment by zcorpan** [comment]
Need to consider workers and worklets also.

**Comment by annevk** [comment]
@zcorpan console is exposed to workers. Dunno about worklets.

**Comment by zcorpan** [comment]
Right, I mean we need to make sure this API invokes the right hooks in those contexts (or define to do nothing or throw if it shouldn't work there). https://html.spec.whatwg.org/multipage/workers.html#runtime-script-errors-2 is different from https://html.spec.whatwg.org/multipage/webappapis.html#runtime-script-errors-in-documents

**Comment by domenic** [comment]
Now that I realize this would trigger window.onerror I no longer think this is a `console` API, for what it's worth. Probably `global.reportException(obj)`.

**Comment by domenic** [comment]
Trying to gather implementer interest over at https://github.com/whatwg/html/pull/1196, for any implementers watching this repo.
