### ISSUE TITLE
console descriptor / enumerability on the global object

### ISSUE THREAD

**Issue by JosephPecoraro** [whatwg/console#55]
Should `console` be enumerable on the global object or not?

Current descriptor attributes in different environments: `Object.getOwnPropertyDescriptor(globalObject, "console")`

* Firefox - getter/setter, configurable: true, enumerable: true (effectively writable)
* node - getter, configurable: true, enumerable: true (effectively not writable)
* Chrome - value, configurable: true, enumerable: true, writable: true
* Safari - value, configurable: true, enumerable: false, writable: true
* Edge - value, configurable: true, enumerable: true, writable: true

With the push in #3 to have `console` be a namespace object like `Math` and `JSON`, then it makes sense to have similar descriptor attributes to those objects. In fact, all environments agree on the descriptor attributes for `Math` and `JSON`. This matches the Safari implementation.

Proposal:

* value, configurable: true, enumerable: false, writable: true

I don't have a strong preference one way or the other.

Would there be an advantage to having `console` be enumerable?

**Comment by JosephPecoraro** [comment]
As a follow-up. When comparing further to `Math` and `JSON`, all their standard properties are non-enumerable, while all `console` implementations currently have enumerable properties. It seems `console` is a fountain of enumerability where ECMAScript objects tend to be more conservative.

**Comment by domenic** [comment]
As discussed in #3, there's still a desire to have Console be definable in Web IDL. In particular, this is an issue not about the behavior of the Console object itself, but of the Window and WorkerGlobalScope objects---which are currently definable entirely in Web IDL.

So I think we should stick with what Web IDL defines, which is what's currently in the spec and is the Firefox behavior: enumerable: true, getter, and a setter that does defineOwnProperty() per https://heycam.github.io/webidl/#Replaceable and accompanying text.

**Comment by JosephPecoraro** [comment]
Ahh, so this is a contention I've been having.

WebKit is not using Web IDL for `console` because it is implemented directly in the JavaScript engine (JavaScriptCore). This allows us to expose `console` to pure JavaScript environments and the same set of tools (Web Inspector) work with these environments just as you would expect. Similar to how node, being a non-browser context, exposes a console object (though I don't know to what degree they would want to follow this spec).

So I tend to think of `console` in ECMAScript land. Providing a Web IDL description of Console itself is not at odds with that.

I now see how the spec handles this now being exposed in Web environments.

```
partial interface Window {
  [Replaceable] readonly attribute Console console;
};

partial interface WorkerGlobalScope {
  [Replaceable] readonly attribute Console console;
};
```

**Comment by domenic** [comment]
Per @bzbarsky's view of how the IDL "namespace" object should work, the answer here would change (https://github.com/whatwg/console/issues/3#issuecomment-217271882). I think it would be that `window.console` would be like `window.HTMLElement` or `window.AnyInterfaceDeclaredInSpecs`, which is `{ enumerable: false, configurable: true, writable: true, value }`.

I really need to work on that IDL patch to add namespaces...

**Comment by bzbarsky** [comment]
Right, so it would be the current Safari behavior.

**Comment by JosephPecoraro** [comment]
Thanks for the update! I am of course very happy with that, as it was my original proposal =).

Can we just close the issue?

**Comment by domenic** [comment]
Well, I think we should leave it open until we get the spec fixed :). Just wanted to make sure you didn't go changing Safari to conform to my https://github.com/whatwg/console/issues/55#issuecomment-216548282 / the current spec.
