### ISSUE TITLE
console.assert with no arguments

### ISSUE THREAD

**Issue by JosephPecoraro** [whatwg/console#56]
What should be the behavior of `console.assert` with no arguments?

Currently the spec shows a single required argument and optional data.

```
interface Console {
  void assert(boolean condition, any... data);
};
```

Most implementations however allow for `console.assert()` to work, and fire an assert:

* Safari, Chrome, Edge, node - length === 0, triggers an assertion message
* Firefox - length === 1, throws an exception - TypeError: Not enough arguments to Console.assert.

I think there is a valid use case for no arguments. `console.assert()` could used by developers as a "Assert Not Reached". It is slightly simpler then `console.assert(false)`, slightly worse than `console.assert(false, "Unhandled type %s", type)`, but effectively equivalent to both.

So it may be appropriate to make the condition itself optional.

Proposal:

```
interface Console {
  void assert(optional boolean condition, any... data);
};
```

I think it is clear that implementations should fire an assert (in any way they wish) when there are no arguments. The implicit `undefined` value for condition is falsey.

**Comment by terinjokes** [comment]
I disagree. It's common for a basic assert to take a boolean followed by `sprintf` compatible datum. We should continue this. Furthermore, making the first parameter of a variadic function optional causes all sorts of problems.

Per #54, implementation should probably shallow the error (the `TypeError` from Firefox) and perhaps print a warning to the user, but shouldn't be observable.

**Comment by JosephPecoraro** [comment]
> It's common for a basic assert to take a boolean followed by sprintf compatible datum.

That behavior is unchanged by this proposal.

> Furthermore, making the first parameter of a variadic function optional causes all sorts of problems.

I think that could be solved by giving the optional parameter a default value:

```
interface Console {
  void assert(optional boolean condition = false, any... data);
}
```

> implementation should probably shallow the error (the TypeError from Firefox) and perhaps print a warning to the user, but shouldn't be observable.

The TypeError from Firefox is not generated by user code, it is `console.assert` itself throwing the exception. So nothing is getting swallowed, but this would require Firefox changing to not emit a runtime exception when there is no argument.

Printing a warning to the user would be fine, but then we are left with: Should this trigger an assertion or not? Since all other implementations currently do, I think it would be reasonable to spec that.

**Comment by domenic** [comment]
Yeah, `void assert(optional boolean condition = false, any... data)` makes sense to me. The only thing it would change is to make `console.assert()` a synoynm of `console.assert(false)`; it wouldn't, for example, make `console.assert("failed assertion")` equivalent to `console.assert(false, "failed assertion")`.

The fact that this aligns with all but one browser is pretty compelling too.
