### ISSUE TITLE
console.count with no arguments

### ISSUE THREAD

**Issue by JosephPecoraro** [whatwg/console#60]
The spec for `console.count()` with no arguments does not match implementation behavior and is not as useful as it could be.

Currently:

```
void count(optional DOMString label = "");
```

With the algorithm roughly being:

```
1. Increment an internal counter for the `label`
2. Log `label: <count>`
```

---

I feel it was originally the intention of `console.count()` with no arguments is to create a unique counter. That way you can have multiple unique counters for their location in source code but use a `label` if you want to increment a shared counter.

There was [discussion on this a long time ago](https://github.com/firebug/firebug/issues/6508) in [multiple places](https://code.google.com/archive/p/fbug/issues/6386) to fix and improve existing implementations, which treated no arguments as (source:line) but should be (source:line:column) to be unique. My proposal at the time was:

```
I'd like to propose the following console.count changes:

    (1) Share console.count(<title>) counters with the same title.
    If you want to increment a "shared" counter in multiple places, that is
    currently only possible if if you manage to put the counters on the
    same line.

    (2) Make each console.count() without a title completely independent.
    If you really want to know exactly how many times a particular console.count has
    been incremented it shouldn't matter what other console.count's appear on the same
    line as that one.
```

It [got some support](https://github.com/DeveloperToolsWG/console-object/pull/22).

---

Current implementation behavior for multiple `console.count()` on the same line still sucks:
- Firefox, Safari, Chrome - all increment the same "line counter" instead of "position counter"
- Edge - increments what looks like an "unnamed counter", which is not the empty string label!
- node - no console.count

Current implementation behavior for `console.count("label")` is roughly equivalent:
- Firefox, Chrome, Edge - all increment the same "label" counter
- Safari - only increments the "label" counter if it is on the same line... (oops)

It is also worth noting that Edge has `console.countReset(label)`. Which works very well when it is required that there is a label. Perhaps if we decide to spec this, then `console.countReset()` with no arguments should probably clear _all_ labels.

---

Proposal:

```
void count(optional DOMString label);
```

Algorithm:

```
1. If no label was provided, let `label` be a unique label for this callsite.
2. Increment an internal counter for the `label`
```

Note:

```
NOTE: An example implementation of creating a unique label for a
console.count callsite would be the (sourceId:line:column)
combination of where the console.count appears. No two
console.counts would share this combination. Whatever the unique
label is, it should not be possible for a user provided label to
increment this unique label. One way this could be achieved by
implementors is internally prefixing user provided labels and engine
generated labels differently, to guarantee no collisions.
```

You'll notice I dropped the spec's current suggestion to `log <label>: <value>`. I think that is outdated. If you increment a counter 100 times, should the developer tools really be spammed with 100 counts? I think developer tools should be given the freedom to display counters without the log. I think there is a wealth of opportunity here and nobody is taking advantage of. A naive browser implementation may be to simplify log the count; a better user experience might be a view that shows all the counters, their values updating live, and the ability to reset and jump to their location.

My wording for the NOTE is not the best. Please help it ;)

**Comment by JosephPecoraro** [comment]
I've long considered just removing `console.count`. I don't see it getting any use. But every time I think about removing it, I think about how much it could be improved and made useful.

I would be most interested in seeing what @DigiTec and @andysterland think from Edge, since they are the closest to this. From what I can understand, in Edge `console.count()` is a globally unique counter. My proposal would be making `console.count()` a callsite / position unique counter.

What are people's thoughts on the differences between a globally unique versus callsite unique?

**Comment by JosephPecoraro** [comment]
[WebKit Bug 157439](https://bugs.webkit.org/show_bug.cgi?id=157439) will get us to match most of Edge's current behavior. Certainly an improvement over what we had before.

**Comment by andysterland** [comment]
Few thoughts... 

I decided to make the counter unique to give developers the flexibility to count items that might not originate from the same callsite. Perhaps they are tracking a user interaction some other high level construct that doesn't nicely translate to one location/event/etc.

Though in Edge you should see the UI update just one entry in the console when `console.count` is called and not add an entry for every increment. Of course, each different label will get a new entry. The downside is it can make it easier to loose the counter as it scolls up in the log and your sttention stays focused at the end. Granted, we should probably change that by moving the counter to the bottom when it's updated but as the feature doesn't seem to be that used we've not made any time for it.

Also, not tracking the call site simplified the implementation both in terms of complexity to implement and the CPU cost of using `console.count`.

Also, I don't think the feature is that useful but it's out there and, at least, for Edge and IE we have no idea of actuall usage as we have no telemetry for the feature. Indeed, all our console.* aren't instrumented in the tools.

**Comment by robertkowalski** [comment]
Hmmm, I feel very unsure here.

As a developer who is also heavily debugging issues I have never used it,
does anyone else use it at all?

**Comment by JosephPecoraro** [comment]
Doesn't sound like my original proposal is getting any traction. Meanwhile, to move WebKit to something somewhat sane I started moving in Edge's direction.

Would everyone be fine with moving towards something like Edge's behavior? They conveniently also expose `console.countReset` which seems harmless to also include.

---

Proposal:

```
void count(optional DOMString label);
void countReset(optional DOMString label);
```

Algorithm:

```
1. If no label was provided, increment or reset a global counter.
2. Otherwise, increment or reset the counter for `label`
```

---

Alternatively, this could have consistency with what we just did for time/timeEnd and be `optional DOMString label = "default"`. Where there is no secret global counter, just the counter labeled "default".

NOTE: I still think the spec should drop the whole logging suggestion. That shouldn't be defined by the spec for the reasons I outlined above.

Any support?

**Comment by robertkowalski** [comment]
Hi @JosephPecoraro,

right now every method on console logs immediately to the console. The `console.count` method has the same behaviour. 

I keep thinking backwards and forward about this. I used `console.count` several times in the past, especially for hairy race conditions in big, ugly spaghetti code. Because the code was very complex I would not have known at which position I should have read the counter. However, there are situations where you place a `debugger` statement or a similar breakpoint and then could interact at runtime.

A buffer for all console-methods I could read from could be useful. We already included the possibility for this behaviour [in the section for the Printer](https://console.spec.whatwg.org/#printer): 

```
If the console is not open when the printer operation is called,
implementations should buffer messages to show them in 
the future up to an implementation-chosen limit 
(typically on the order of at least 100).
```

I'm curious what @terinjokes  and @domenic say – and if there would be support from the implementors.

**Comment by terinjokes** [comment]
There's at least two proposals here, please let me know if I've missed another.

1. **remove logging from counters**. I agree that we probably don't need to specify how a user-agent displays counters. A naïve implementation may, of course, continue to log as `label: count`.

  Are counters already accounted for the various serializations, such as Selenium and the remote debugging protocols? Or are they relying on the user-agent to print them to the log?
2. **label-less counters**. A benefit to having a default label is that there are no special counters to handle. But I'd prefer implementors to weight in on this one.

**Comment by robertkowalski** [comment]
related: https://github.com/whatwg/console/pull/61

**Comment by robertkowalski** [comment]
@JosephPecoraro addition: to me the behaviour of edge (not counting empty strings with the same counter as no arguments given) makes sense. if implementors decide for a new "default" label `console.count("default")` would raise the counter, right?

**Comment by JosephPecoraro** [comment]
>  if implementors decide for a new "default" label console.count("default") would raise the counter, right?

Yes

**Comment by domenic** [comment]
I tend to agree with the plan to move toward the Edge-like behavior. I think using `= "default"` is a good touch. And adding `countReset` makes sense; in general most implementers of console APIs probably want the union of all available APIs.

The question of whether logging behavior should be mandated is an interesting, and probably separate, one. My thoughts are that the current spec gives the appropriate level of flexibility while still giving guidance and precision that is useful for implementers. It gives detailed instructions for how to match user expectations all the way up to the "Printer" abstract op, which it leaves implementation-defined. Implementations can do whatever they want at that point.

Perhaps the current situation could be slightly improved by generalizing the first argument. Right now it is one of a set of strings ("error", "log", "warn", ...) and some methods reuse those strings (e.g. count and debug reuse "log"; trace and error reuse "error"). This might be seen as too restrictive, implying that count() must print in the exact same way as log(). Perhaps if instead the first argument became something like "source", and it was a different string for every method, it would be clearer that implementations can vary how they print (or don't print) depending on what method was called.

**Comment by domenic** [comment]
Let us split this into three issues:

- https://github.com/whatwg/console/issues/88 will cover the behavior if no arguments were passed
- A new issue to cover the spec being kind of inaccurate about how logging occurs for counters
- A new issue to contemplate adding console.countReset.

**Comment by robertkowalski** [comment]
yes this stalled, was living in the illusion some day an implementor would
read the discussion and everything gets solved then, but things get lost
too easy.

thanks domenic! :)
