### ISSUE TITLE
It is not possible for Node.js to implement clear()

### ISSUE THREAD

**Issue by Fishrock123** [whatwg/console#76]
Node.js does not have access to what stdio (e.g. console) data goes to. Once it has gone through "the pipe" we are usually not able to alter it.

Currently Node.js has 4 possible output options for console (stdout/stderr) output:

- Terminal (TTY)
  - Only "clear-able" by control codes, sorta, in some terminals. Unreliable.
- Pipe
  - Dependant on the consumer, not possible.
- File
  - We _could_ clear the file, getting any of to agree to it will be a challenge, I think.
- TCP Socket
  - Yeah, you can actually have Node.js stdio (and console) write to / read from a TCP socket. I have no idea what implications this has.

**Comment by domenic** [comment]
Again, it looks like Node.js is fully able to conform to [the spec](https://console.spec.whatwg.org/#clear) here, and there is no problem:

> If possible for the environment, clear the console. Otherwise, do nothing.

**Comment by Fishrock123** [comment]
Hmmm, nice. I suppose I working mainly off of the previous "spec".
