### ISSUE TITLE
define formatting specifiers

### ISSUE THREAD

**Issue by jsinmotion** [whatwg/console#78]
Question: are strings like `%6.9f` formatting specifiers?

As of commit 79390cb5727d0d89f70cc4902442ae824f010c19 the answer seems to be no, but chrome and firefox both treat it as a specifier:

```js
> console.log("|%6.9f|",1.23)
|1.23|
```

**Comment by domenic** [comment]
This seems pretty well-defined in the spec. What about the current algorithm do you find unclear? (It does not treat those as format specifiers.)

Now, we might want to change the spec... Currently the results I see are:

- Chrome: treats as %f
- Firefox: some kind of numeric specification thing (changes the sigfigs)
- Edge: does not treat as a format specifier:
- Safari TP: cannot even test as I am getting weird painting artifacts in dev tools

**Comment by domenic** [comment]
Restarted and Safari was working better. That leaves us with not great interop, but at least 2/5 implementations are following the spec. The alternative would be to do something Firefox/Safari-like I guess.

**Comment by jsinmotion** [comment]
@domenic another example: according to the spec, `console.log("%%s %s", "foo")` should be "%foo %s" since it does not understand the `%%` to escape the percentage, but chrome and safari both do it.

IMHO merely saying "Find the first possible format specifier specifier, from the left to the right in target." without actually defining "format specifier", seems vague.  POSIX printf defines the format specifier in more concrete terms: http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html

```
Each conversion specification is introduced by the '%' character [CX] [Option Start]  or by the character sequence "%n$", [Option End]  after which the following appear in sequence:

Zero or more flags (in any order), which modify the meaning of the conversion specification.

An optional minimum field width. If the converted value has fewer bytes than the field width, it shall be padded with <space> characters by default on the left; it shall be padded on the right if the left-adjustment flag ( '-' ), described below, is given to the field width. The field width takes the form of an <asterisk> ( '*' ), described below, or a decimal integer.

An optional precision that gives the minimum number of digits to appear for the d, i, o, u, x, and X conversion specifiers; the number of digits to appear after the radix character for the a, A, e, E, f, and F conversion specifiers; the maximum number of significant digits for the g and G conversion specifiers; or the maximum number of bytes to be printed from a string in the s [XSI] [Option Start]  and S [Option End]  conversion specifiers. The precision takes the form of a <period> ( '.' ) followed either by an <asterisk> ( '*' ), described below, or an optional decimal digit string, where a null digit string is treated as zero. If a precision appears with any other conversion specifier, the behavior is undefined.

An optional length modifier that specifies the size of the argument.

A conversion specifier character that indicates the type of conversion to be applied.
```

**Comment by domenic** [comment]
I see. The intent is that it's supposed to be detailed in the following steps (3.a-3.f), but a clarification PR wouldn't hurt.
