### ISSUE TITLE
Node.js console.dir

### ISSUE THREAD

**Issue by Fishrock123** [whatwg/console#79]
Node.js has implemented a [`console.dir(obj[, options])`](https://nodejs.org/dist/latest-v7.x/docs/api/console.html#console_console_dir_obj_options) since Node v0.1.101.

From what I can tell, it appears to be a more direct sort of proxy to [`util.format()`](https://nodejs.org/dist/latest-v7.x/docs/api/util.html#util_util_inspect_object_options) allowing the passing of options rather than additional objects.

**Comment by domenic** [comment]
dir is tracked in https://github.com/whatwg/console/issues/27 FWIW. Someone should really fix that... slapping "good first bug" on it doesn't seem to be working :)

**Comment by domfarolino** [comment]
This can be closed since `dir` has been added but I noticed browser implementations don't seem to support the optional `options` object that Node does. It also doesn't seem really applicable to browser implementations but I'm wondering if the API difference matters at all, or if we should at least make a note about it in the spec?

**Comment by domenic** [comment]
Hmm. This is a case where I think it doesn't hurt anyone to include special optional Node.js-only provisions. E.g. an optional argument for the options which anyone can use to customize the behavior of Printer, but in practice only Node.js uses this flexibility.

Based on [the source code](https://github.com/nodejs/node/blob/ed12ea371c5352b4b13f9f1c4e0f577fbd30bb2a/lib/console.js#L126) in Node plus [the definition of Object.assign](https://tc39.github.io/ecma262/#sec-object.assign) it looks like IDL of `optional object? options` would be equivalent. I believe such IDL cannot throw any exception, and I know it will not impact `console.dir.length`, so browsers that totally ignore the argument will be compliant.

Then we could modify step 2 to say something vague like "optionally using the properties of the _options_ object to customize display". Or we could add a third arg to Printer, pass it through, and add a sentence about optionally using the third arg (if it is not undefined or null) to customize the display; that might be cleaner.

The only possible downside of this is that it constrains browsers from ever using the second argument in some different way. But that doesn't seem like a realistic fear.

**Comment by domfarolino** [comment]
Yes I favor the third arg over the method doing stuff that is in Printer's domain. The optional + nullable options object sounds good thanks for digging in. Going to reopen this until I take care of it.
