### ISSUE TITLE
Intermediate values with console.time

### ISSUE THREAD

**Issue by mattzeunert** [whatwg/console#84]
There should be a way to print how much time has passed since a timer has started without removing the timer.

In Chrome calling `timeEnd` currently doesn't remove the timer, so you can call timeEnd multiple times.

    console.time("abc")
    console.timeEnd("abc")
    console.timeEnd("abc")
    // abc: 0.006ms
    // abc: 0.281ms

The timer is reset only when `time` is called again with the same label. Firefox and Node remove the timer when `timeEnd` is called, as the spec says.

To be able to see intermediate values the spec could either be changed to recommend Chrome's behavior, or a new `timeLog` (or similar) function could be introduced, which prints the duration without affecting the timer itself.

    console.time("abc")
    console.timeLog("abc")
    console.timeEnd("abc")

**Comment by JosephPecoraro** [comment]
I think this is a great idea. It would be easy to implement this in WebKit. I'd be happy to do it.

**Comment by domenic** [comment]
> I think this is a great idea. It would be easy to implement this in WebKit. I'd be happy to do it.

The new timeLog function ,or the timeEnd-can-be-called-multiple-times behavior?

/cc @paulirish @auchenberg

**Comment by JosephPecoraro** [comment]
Allowing `timeEnd` to be called multiple times. Its pretty similar to `performance.measure` as well.

**Comment by targos** [comment]
Anyone knows when (and why) did Chrome's behavior change? According to https://github.com/nodejs/node/pull/3562, it used to remove the timer after a call to `timeEnd`.

**Comment by JosephPecoraro** [comment]
It looks to me like [this change](https://chromium.googlesource.com/chromium/src/+/807ec9550e8a31517966636e6a5b506474ab4ea9%5E%21/) / [(review)](https://codereview.chromium.org/1859293002). Not sure if that was intention or not as it doesn't appear to be mentioned in the commit message, but code inspection looks like it might have done it (see difference between `ConsoleBase::timeEnd` and `timeEndFunction`).

**Comment by domfarolino** [comment]
As of at least now Chrome's behavior is back to removing the timer from the associated [timer table](https://console.spec.whatwg.org/#timer-table). In other words, `timeEnd` cannot be called more than once (effectively) in any implementations. With this, would it be more sensible to:

 - Ask all implementations to change their behavior of `timeEnd`
 - Add a `timeLog` function

I'd be happy to implement either in Chrome, but I'd like to here from @JosephPecoraro (who likely still prefers multiple calls to `timeEnd`) and @paulirish, @bgrins, and @xirzec

**Comment by xirzec** [comment]
I prefer adding a new timeLog function, since then it can be more easily feature detected.

**Comment by bgrins** [comment]
cc: @nchevobbe @bakulf

I also prefer a new function because:
1) the naming of `timeEnd` implies it the timer is going away
2) as @xirzec mentions, devs could detect if an implementation supports it and do something else if not

**Comment by bakulf** [comment]
Makes sense to me and it seems we have consensus here.
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1458466 to implement it in firefox.

**Comment by mattzeunert** [comment]
I'm wondering, perhaps it might be helpful to have an extra label as well that gets printed on the same line:

```
console.time("Load Page")
console.timeLog("Load Page", "JSON loaded")
console.timeLog("Load Page", "App rendered")
console.timeEnd("Load Page")
```

**Comment by nchevobbe** [comment]
> I'm wondering, perhaps it might be helpful to have an extra label as well that gets printed on the same line

I think that would make sense. I used to do things like : 

```js
console.group("Load Page");
console.time("load json");
console.timeEnd("load json");
console.time("app rendered");
console.timeEnd("app rendered");
console.groupEnd("Load Page");
```

so with `timeLog` + an additional label that could be really nice.
The secondary label could be rendered with a grey-ish color so the emphasis would still be on the primary one.

**Comment by domfarolino** [comment]
The extra label seems pretty helpful with this intermediate `timeLog` idea. Seems like we at least have consensus (or just about all the way there) on `timeLog`. Seems like @bakulf has started a FF implementation, are you comfortable updating it to support multiple labels? Would like to double-check with @xirzec as well as @JosephPecoraro and then I'll start speccing it out!

**Comment by bakulf** [comment]
Instead of having an extra DOMString parameter, I think it would be better to have:
`void timeLog(optional DOMString label = "default", optional any... data);`
This makes timeLog similar to assert(), log() and so on.

**Comment by nchevobbe** [comment]
For the record, this landed in Firefox 62.0a1 (2018-05-22) (See [Bug 1461001](https://bugzilla.mozilla.org/show_bug.cgi?id=1461001))

**Comment by domfarolino** [comment]
@nchevobbe Great to hear, thanks for the update! I'll get a spec PR going.

**Comment by domfarolino** [comment]
I've posted a PR for this, would welcome anyone taking a look and providing feedback.

**Comment by domfarolino** [comment]
If anyone (@nchevobbe perhaps since FF has implemented) wants to check out the spec PR https://github.com/whatwg/console/pull/138 for this that'd be great! We should be able to land this relatively soon, just want to get some eyes on the PR before I write some tests.
