### ISSUE TITLE
Clarify that console.assert should log even without formatting string

### ISSUE THREAD

**Issue by sirlantis** [whatwg/console#85]
https://console.spec.whatwg.org/commit-snapshots/36c3ee56b8471c82ec5ea88dcbaf223235b22a3e/#assert

> If condition is false, perform Logger\("error", data\)\.

A call like `console.assert(false)` would then call `Logger("error", [])`, but the implementation of `Logger` states as the first item:

> 1. If `args` is empty, abort these steps.

I would expect the behavior to log something though - and the participants in the discussion around #56 seem to make the same assumption.

When calling `console.assert(false)` in various browsers, something is logged in that case:

- Chrome prints `Assertion failed: console.assert` with level *error*
- Safari prints `Assertion Failed` with level *error*
- Firefox prints an empty line with level *error*
- Edge prints `undefined` with level *error*
- Node throws an `AssertionError: false == true` (`false` is static, same result for `console.assert(0)`)

I'd propose to add a section that clarifies this:

1. If condition is *true*, abort these steps.
2. If *data* is not empty, perform Logger("error", *data*). Abort these steps.
3. Let *message* be the string "Assertion failed".
4. Perform Logger("error", [*message*])

Should we make a clear recommendation of what the String in (3) should look like? Or leave it open to implementers, e.g. just say "a string, indicating that some assertion failed (e.g. ...)"?

---

For reference, calling `console.assert(false, "foo")` in various browsers:

- Chrome prints `Assertion failed: foo` with level *error*
- Safari prints `Assertion Failed: foo` with level *error*
- Firefox prints `foo` with level *error*
- Edge prints `foo` with level *error*
- Node throws an `AssertionError: foo`

EDIT: Didn't have access to Edge, added @domenic's findings.

**Comment by domenic** [comment]
Great catch!

For the record, `console.assert(false)` in Edge gives a red "undefined"; `console.assert(false, "foo")` in Edge gives a red "foo".

I think we should not mandate specific strings, but we can offer suggestions.

It also sounds like we should allow (maybe encourage?) inserting a string like "assertion failed: " at the front of _data_ if _data_ is not empty.

So maybe something like:

1. If condition is true, abort these steps.
1. If data is not empty, implementations should prepend a string indicating that the following message is being logged to indicate an assertion failure (such as "Assertion failed:") to data.
1. Otherwise, append a string indicating generically that an assertion failed (such as "Assertion failed") to data.
1. Perform Logger("error", data).

WDYT?

**Comment by sirlantis** [comment]
Sounds good in general. However (2) would not allow for formatting:

```js
console.assert(false, "foo: %s", "bar") // would print "Assertion failed: foo %s bar"
```

- Chrome: `Assertion failed: foo %s bar` (as mentioned in NOTES.md)
- Safari: `Assertion Failed: foo bar`
- Firefox: `foo: bar`
- Edge: (not tested, but I'll assume identical to Firefox)

So Safari concatenates the general assertion failure string with the formatting string. However it does not do so, if the first argument isn't a string. For `console.assert(false, {answer: 42})` it prints "Assertion Failed" and then the object as an "additional parameter" (which is foldable/highlighted).

My personal opinion is that Safari does the "correct" thing with not breaking formatting capabilities. Following that this would be the revised version:

1. If _condition_ is true, abort these steps.
1. Let _message_ be a string without any formatting specifiers indicating generically an assertion failure (such as "Assertion failed").
1. If _data_ is empty, append _message_ to _data_.
1. Otherwise, implementations should perform these substeps:
    1. Let _first_ be the first element of _data_.
    1. If _first_ is not a string, prepend _data_ with _message_.
    1. Otherwise, perform these substeps:
        1. Let _concat_ be the concatenation of _message_, U+003A COLON (:), U+0020 (SPACE), and _first_.
        2. Replace the first element of _data_ with _concat_.
1. Perform Logger("error", _data_).

I put this up as a PR in #86.

**Comment by sirlantis** [comment]
In summary:

- Safari would follow the spec.
- Chrome would use "Assertion failed:" as _message_, diverge a bit in 3 (as it also appends ": console.assert" in that case), and not follow the recommendation 4.iii (instead naively prepending it).
- Firefox/Edge would use an empty string (sarcastically speaking it's the _most generic_) for _message_ and not follow the recommendation 4.iii.a (the colon+space concatenation).
