### ISSUE TITLE
The spec for console.count() implies it should log every time

### ISSUE THREAD

**Issue by domenic** [whatwg/console#90]
https://github.com/whatwg/console/issues/60 discusses an issue with the current spec for console.count(), which says

> Perform Logger("log", concat).

But given code like

```js
console.count("a");
console.count("a");
```

implementations will generally not log

```
a: 1
a: 2
```

but instead will update the first line to say "a: 2".

----

Now, since Printer (called by Logger) is implementation defined, the spec actually allows this just fine. But it's pretty unclear. It's also a bit strange since we do `Logger("log", concat)`, so the implementation would have to use some out-of-band magic to remember that this `"log"` is not the same as `console.log()`s `"log"`.

Personally I think the best fix would be:

- Introduce a new log level, "count", and use it in the definition of console.count()
- Add a sentence in the description of Printer that talks about what implementations often do for a log level of "count".

**Comment by domfarolino** [comment]
A tad confused here...from what I can tell copying

```js
console.count("a");
console.count("a");
```

into the DevTools gives

```js
a: 1
a: 2
```

in Chrome + Canary, Safari + Tech Preview, and Firefox 52. I vaguely remember it was Edge that was prone to updating a previously "logged" counter when calling `count(existingLabel)` from a previous discussion. With that being said, is this just an edge thing or am I missing something?

**Comment by domenic** [comment]
Huh, for some reason I could swear I observed the counter-updating behavior in some browser. But re-reading #60 it looks like @JosephPecoraro was mainly suggesting that it be allowed, not that browsers already do it. I guess that decreases the urgency here...

**Comment by JosephPecoraro** [comment]
From https://github.com/whatwg/console/issues/60#issuecomment-217998248:

> In Edge you should see the UI update just one entry in the console when console.count is called and not add an entry for every increment.

**Comment by xirzec** [comment]
I was actually going to change Edge to behave like Chrome/Safari/FireFox and log each time to be consistent. Is this not desirable?

**Comment by domfarolino** [comment]
Personally I like the consistency. I think the reason the issue was raised was because we noticed the odd behavior with Edge. I am in favor of this changing for consistency though, thoughts from anyone else?

**Comment by JosephPecoraro** [comment]
It still feels to me like things are being over-specified without actually thinking through what would actually be useful for developers.

I view `console.count` as being about incrementing a counter and having developer tools provide a way to view the value of the counter.

Things that would need to be defined are:

  * How the counters are created / named / shared
  * How the counters can be incremented, decremented, or cleared

Things that would not need to be defined are:

  * How the counters are displayed

Different tools may provide different user experiences for showing the counts. For example (1) a log to the console every single time the counter happens, or (2) having a single display for a named counters and showing its current value.

Every time I see `console.count` expressed in terms of `Logger(...)` or console messages, I immediately feel disappointed and disinterested in the discussion. Does anyone else feel the same, or have the same concerns that I have? Maybe my conception of what `console.count` is and how developers use it is inaccurate?

---

> I was actually going to change Edge to behave like Chrome/Safari/FireFox and log each time to be consistent. Is this not desirable?

I think I said it before, but if not I'll voice it now. I think Edge provides the best user experience for counters right now. I'd bring the same to WebKit (and go further) if I felt `console.count` was used enough to warrant the time investment. Unfortunately it hasn't become a priority for me.

**Comment by xirzec** [comment]
Edge has console.countReset() for setting them back to zero. Incrementing the same message is nice from an "avoid spam" perspective, but I find that it quickly gets scrolled off the screen in practice (unless it is the only thing being logged, in which case log de-duplication would have solved the problem.) 

Decrementing is interesting, but I guess my real trouble is that I have a hard time understanding the scenario this feature is trying to address. 

It seems to me that this entire feature can be implemented in app code trivially, so is the goal to provide a convenient shortcut? Or are developers using it in a dynamic fashion such as putting console.count() in a conditional breakpoint in order to understand how many times a codepath is executed without changing app code?

**Comment by domenic** [comment]
> It still feels to me like things are being over-specified without actually thinking through what would actually be useful for developers.

Although I wouldn't state it that strongly, I tend to agree we should be more cautious about over-specifying UI. I think using abstractions like Logger/Printer is fine. But I think we should be generally more explicit about how these are truly up to the browser and what experience it wants to provide. The OP of this post is about trying to help with that phrasing in some very specific ways. Maybe it should be a more general issue about trying to make it clearer that printing is implementation-defined and a good place for UX innovation. For example:

1. Splitting up every (?) method to use a distinct printer string (so "log" doesn't get reused so much), but including an informative table on common groupings (so you can tell that most implementations print console.log() and console.debug() in similar ways). This makes it clearer that the different method names give implementations room to innovate on UX in a way that's easy to read off from the spec, instead of out of band.
2. Providing several examples of ways that applications could do innovative things with Printer. Off the top of my head:
   - Deduping identical subsequent messages
   - Special count behavior as discussed here
   - Constantly-running timers
   - Extra UX off to the side displaying counters/timers
   - Very loud behavior (such as flashing the console background red) for failed asserts

> I think I said it before, but if not I'll voice it now. I think Edge provides the best user experience for counters right now.
>
> Decrementing is interesting, but I guess my real trouble is that I have a hard time understanding the scenario this feature is trying to address.

Personally I think the best possible use of console.count() is in scenarios where you're not sure how much a code path is going to be hit. For example, a loop which breaks according to a condition---how many iterations happen before that condition comes to pass? It allows you to avoid setting up an appropriately-scoped state variable by making the browser do the bookkeeping in its side-table.

I don't know if that matches how it's used in the real world. Maybe we can get some people to weigh in if I tweet about it. But that's what I'd optimize toward.

As such I do agree that Edge provides the best current UX. Probably it could be even better with smart de-duping: e.g. `console.count("a"); console.log("x"); console.count("a");` prints three lines, but `consle.count("a"); console.count("a");` only prints one line and then updates it. This would solve the scrolling off the screen problem while still retaining Edge's advantages in terms of making it a useful, non-spammy way to count things.

But as @JosephPecoraro alludes to, it's really unclear whether developers use this function at all, and thus whether it's worth implementations' time to work on the UX. Maybe developers would use it more, if it were better? Who knows.
