### ISSUE TITLE
Grouping methods

### ISSUE THREAD

**Issue by domfarolino** [whatwg/console#94]
The mechanics of the console [grouping methods](https://console.spec.whatwg.org/#grouping) `group()`, `groupEnd()`, and `groupCollapsed()` are pretty straightforward and fairly consistent between implementations (have not tested edge) with the exception of Node (not implemented) and Firefox (shipping collapsible groups in [v54](https://bugzilla.mozilla.org/show_bug.cgi?id=1088360#c35)).

I'm concerned with how Printing is done inside of a group, and how we might describe it. While thinking about how I might implement this in the reference implementation, I came up with something nearly identical to [this](https://github.com/Rich-Harris/node-console-group/blob/master/src/index.js#L7) module which implements the grouping methods (with the exception of `groupCollapsed()`) in Node. It works by maintaining a `prefix` that is modified when grouping functions are called, and is prepended to data before it is printed.

With that being said, I'm thinking we need to include some rhetoric in [Printer](https://console.spec.whatwg.org/#printer) that briefly explains the idea of a prefix that is prepended messages before they get printed. It is probably worth mentioning that the prefix is initially empty. Similarly, for the grouping methods we can include language explaining how the prefix is modified on calls to `group()` and `groupEnd()`. Should we explain that when a group creation method is called, all future Printing is focused inside of a newly created potentially-collapsible representation of an indented group whose members all share the same prefix? The exact characters these methods append to the prefix is *too* specific I think, since it seems to be an implementation-dependent way of indicating indentation:

Chrome:

<img width="288" alt="screen shot 2017-03-12 at 3 38 21 pm" src="https://cloud.githubusercontent.com/assets/9669289/23835227/fafdba00-0739-11e7-9b4c-5bd69293bb16.png">

FF:

<img width="215" alt="screen shot 2017-03-12 at 3 39 40 pm" src="https://cloud.githubusercontent.com/assets/9669289/23835240/3f704d56-073a-11e7-9565-95d88f8c7229.png">

Safari:

<img width="186" alt="screen shot 2017-03-12 at 3 40 27 pm" src="https://cloud.githubusercontent.com/assets/9669289/23835241/44aa20ee-073a-11e7-9f30-5cdaf4c6e1c5.png">

I also propose that if an environment does not support collapsible groups, that the behavior of `groupCollapsed()` is the same as `group()`. This is partially due to historical reasons, as Firefox has done this for pretty much as long as `group()` has been supported, and so that Node can still support calls to this method without throwing.

My next concern is the default group label if none is provided. Do we simply make it the name of the function called as Chrome does, or an empty string as Firefox and Safari do?

Thoughts?

Some useful code I used while writing this up: https://jsbin.com/tutiho/edit?js,console

**Comment by domenic** [comment]
> With that being said, I'm thinking we need to include some rhetoric in Printer that briefly explains the idea of a prefix that is prepended messages before they get printed. It is probably worth mentioning that the prefix is initially empty.

I'm not sure a prefix is the right way to think about this, especailly for interactive consoles. Maybe a "nesting level" or "group"? Then we can have the spec normatively book-keep the nesting level, and then have Printer say something vague about how the nesting level modifies what's printed?

> Should we explain that when a group creation method is called, all future Printing is focused inside of a newly created potentially-collapsible representation of an indented group whose members all share the same prefix?

Yes, that makes sense to me (modulo "prefix" sounding like an even worse name in this context).

> I also propose that if an environment does not support collapsible groups, that the behavior of groupCollapsed() is the same as group()

The same meaning "they both do nothing"? Or something else?

> My next concern is the default group label if none is provided. Do we simply make it the name of the function called as Chrome does, or an empty string as Firefox and Safari do?

Edge also does empty string. However, I'm loathe to say that Chrome can't do this, when it probably provides a better UX. Maybe "should" be the empty string? Or maybe other UAs (@JosephPecoraro @andysterland) are interested in converging on `"console.group"` as the default label like Chrome does?

**Comment by domfarolino** [comment]
> I'm not sure a prefix is the right way to think about this, especailly for interactive consoles..

I agree, on second thought my comment makes a lot less sense, since the idea of text being in an interactive group has nothing to do with how nested that group is (i.e. how far away from the left pane it appears). We could just define what a `group` is, and mention that Prints should happen inside of it (keep reading).

> The same meaning "they both do nothing"? Or something else?

I guess I meant that they both should produce non-interactive groups at the very least. `group()` tries to create indented interactive groups that are expanded by default when it can, and "static" non-interactive groups when it can't. `groupCollapsed()`, to me, sounds like the groups will be interactive (assuming collapsed things can become un-collapsed). However on non-interactive environments I'm thinking it should produce output similar to `group()` so that it still kind of works (even though it is not collapsed)? We see this behavior in Firefox right now actually. So maybe something like the following would be sufficient:

 - A `group` is a view for Prints with one further level of indentation than its parent.
 - `group()` creates and displays a new `group`. If the environment supports interactive groups, the group should be expanded by default.
 - `groupCollapsed()` creates and displays a new `group`. If the environment supports interactive groups, the group should be collapsed by default.

Then maybe in Printer we say something like "When a `group` gets created, all `Prints` take place in this `group` until a call to `groupEnd()` is made, guiding future prints outside the `group` to its immediate parent, which may also be a `group`".

**Comment by JosephPecoraro** [comment]
RE: Default group label.

> Edge also does empty string. However, I'm loathe to say that Chrome can't do this, when it probably provides a better UX. Maybe "should" be the empty string? Or maybe other UAs are interested in converging on "console.group" as the default label like Chrome does?

Again, I think specifying exact strings like these are unnecessary and unhelpful.

I agree, an empty string is not useful and we (WebKit) should use something better. But I don't think specifying an exact string to use here is a good idea. (1) There is no way to automate tests for this. (2) Specifying an exact string would not be good for localization.

I think cases like these should be user agent defined, like dialog text and error messages. The spec can certainly provide suggestions and reasons for why the suggestions would be useful, but implementations should be free to produce a UX that matches their environment / platform.
