### ISSUE TITLE
Format specifiers in dirxml

### ISSUE THREAD

**Issue by domfarolino** [whatwg/console#99]
As of now `console.dirxml("Dom %s", "Farolino", document.createElement('h1'))` will print:

 > Dominic Farolino *\<h1>*

in Chrome and Safari though the spec does not account for it. This format specifier substitution does not take place in Firefox, and I'm not sure about Edge's behavior.

In the spec I think we should make a call to `Formatter(...` inside `dirxml`, as this functionality exists in at least two browsers. Furthermore it seems that the call to `Formatter(...` must come after we iterate through the *`...data`* transforming DOM elements into their optimal form because `console.dirxml("%O", document.createElement('h1'))` prints the JavaScript object representation of the `h1` element in Chrome and Safari, indicating that the format specifier has the last say.

If Edge also includes format specifier behavior, I think we simply file a Firefox bug and add it to the spec.

**Comment by domenic** [comment]
Edge does not do the substitution, FWIW. But speccing the substitution and filing bugs sounds good to me despite a 2/2 split, since it's likely more useful and symmetric this way.

**Comment by domfarolino** [comment]
I'll put a PR up for this.

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1350572
Edge bug: https://twitter.com/domfarolino/status/845723844862246912 (Used the twitter thing because online issue submissions are apparently broken)
